title: 我的人生游戏
author: cyborgX396
description: 只是小日志罢了。
theme: minima

url: "https://cyborgtimesplus401.github.io"
baseurl: ""

# 构建设置
markdown: kramdown
timezone: China/Beijing
show_excerpts: true

# 顶部导航
header_pages:
  - about.md
